# 🐼 Pandas – Selecting Data
### Interview-focused Practice | Dataset: Employee Records

**Columns:** `employee_id`, `name`, `age`, `gender`, `department`, `city`, `salary`, `experience_years`, `rating`, `joining_year`, `is_manager`, `projects_completed`

**Methods you will practice:**
`df['col']` · `df[['col1','col2']]` · `df.loc[]` · `df.iloc[]` · `df.at[]` · `df.iat[]` · `df.filter()` · `df.query()`

---
> ⚠️ All code cells are empty. Write your own answers!

---
## ⚙️ Setup – Run This First!

In [1]:
import pandas as pd
df = pd.read_csv('employees_dataset.csv')
print('✅ Dataset loaded!')
df.head()

✅ Dataset loaded!


,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42


---
## 🟢 EASY (Q1–Q10)
### Single column, multiple columns, basic loc/iloc

### Q1. Select and display only the `name` column.

In [3]:
df['name'].head()

0    Arjun Sharma
1      Priya Nair
2     Rohan Mehta
3     Sneha Patel
4       Kiran Rao
Name: name, dtype: object

### Q2. Select and display the columns `name`, `department`, and `salary` together.

In [5]:
df[['name', 'department','salary']].head()

,name,department,salary
0,Arjun Sharma,Engineering,95000.0
1,Priya Nair,Marketing,72000.0
2,Rohan Mehta,Engineering,110000.0
3,Sneha Patel,HR,55000.0
4,Kiran Rao,Finance,130000.0


### Q3. Select the first row using `iloc`.

In [7]:
df.iloc[0,]

employee_id                    101
name                  Arjun Sharma
age                             32
gender                        Male
department             Engineering
city                     Bangalore
salary                     95000.0
experience_years                 8
rating                         4.5
joining_year                  2016
is_manager                    True
projects_completed              23
Name: 0, dtype: object

### Q4. Select the last row using `iloc`.

In [8]:
df.iloc[-1,]

employee_id                    125
name                  Aditi Sharma
age                             30
gender                      Female
department             Engineering
city                        Mumbai
salary                     97000.0
experience_years                 7
rating                         4.4
joining_year                  2017
is_manager                   False
projects_completed              24
Name: 24, dtype: object

### Q5. Select rows at index positions 2, 3, and 4 using `iloc`.

In [9]:
df.iloc[[2,3,4]]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42


### Q6. Select the row where the index label is `3` using `loc`.

In [10]:
df.loc[3]

employee_id                   104
name                  Sneha Patel
age                            26
gender                     Female
department                     HR
city                    Ahmedabad
salary                    55000.0
experience_years                3
rating                        4.7
joining_year                 2021
is_manager                  False
projects_completed              8
Name: 3, dtype: object

### Q7. Select rows 0 to 4 and columns `name` and `salary` using `loc`.

In [15]:
df.loc[0:4,['name','salary']]

,name,salary
0,Arjun Sharma,95000.0
1,Priya Nair,72000.0
2,Rohan Mehta,110000.0
3,Sneha Patel,55000.0
4,Kiran Rao,130000.0


### Q8. Select the first 5 rows and first 3 columns using `iloc`.

In [16]:
df.iloc[:5,:3]

,employee_id,name,age
0,101,Arjun Sharma,32
1,102,Priya Nair,28
2,103,Rohan Mehta,35
3,104,Sneha Patel,26
4,105,Kiran Rao,40


### Q9. Get the exact salary value of the employee at row index 0 using `at`.

In [19]:
df.at[0,'salary']

95000.0

### Q10. Get the value at row position 2, column position 5 using `iat`.

In [21]:
df.iat[2,5]

'Delhi'

---
## 🟡 MEDIUM (Q11–Q20)
### loc vs iloc, filter, query, slicing — the kind of things interviewers actually ask

### Q11. What is the difference between `loc` and `iloc`? Write a comment explaining it, then demonstrate with one example each using the dataset.

In [22]:
# loc: searches using index lables(names) 
# iloc: searches using index position
df.loc[0:2, ['name', 'salary']]
df.iloc[0:3, 0:2]

,employee_id,name
0,101,Arjun Sharma
1,102,Priya Nair
2,103,Rohan Mehta


### Q12. Select all columns that contain the word `score` or `salary` in their name using `df.filter()`.

In [27]:
# df.filter(items= ['score','salary']) 
df.filter(regex='score|salary')

,salary
0,95000.0
1,72000.0
2,110000.0
3,55000.0
4,130000.0
5,88000.0
6,68000.0
7,98000.0
8,51000.0
9,115000.0


### Q13. Use `df.query()` to select all employees who have more than 10 years of experience.

In [29]:
df.query('experience_years > 10')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40


### Q14. Use `df.query()` to find employees in the `Engineering` department with a rating above 4.3.

In [38]:
df.query("department == 'Engineering' and rating > 4.3 ")

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24


### Q15. Select every other row (alternate rows: 0, 2, 4, 6...) using `iloc` slicing.

In [40]:
df.iloc[::2]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25


### Q16. Select the last 3 columns of the dataset for all rows using `iloc`.

In [43]:
df.iloc[:,-3:].head()

,joining_year,is_manager,projects_completed
0,2016,True,23
1,2019,False,14
2,2013,True,31
3,2021,False,8
4,2008,True,42


### Q17. Set `employee_id` as the index, then use `loc` to fetch the row for employee `105`.

In [48]:
df.set_index('employee_id').loc[105]
# df.loc[105]

name                  Kiran Rao
age                          40
gender                     Male
department              Finance
city                  Bangalore
salary                 130000.0
experience_years             16
rating                      4.1
joining_year               2008
is_manager                 True
projects_completed           42
Name: 105, dtype: object

### Q18. Use `df.filter(items=[])` to select only the columns `name`, `city`, and `is_manager`.

In [50]:
df.filter(items=['name', 'city','is_manager'])

,name,city,is_manager
0,Arjun Sharma,Bangalore,True
1,Priya Nair,Mumbai,False
2,Rohan Mehta,Delhi,True
3,Sneha Patel,Ahmedabad,False
4,Kiran Rao,Bangalore,True
5,Divya Iyer,Chennai,False
6,Aditya Kumar,Delhi,False
7,Meera Joshi,Pune,True
8,Vivek Singh,Mumbai,False
9,Ananya Das,Kolkata,True


### Q19. Use `df.filter(like='')` to select all columns whose name contains the word `year`.

In [51]:
df.filter(like='year')

,experience_years,joining_year
0,8,2016
1,5,2019
2,11,2013
3,3,2021
4,16,2008
5,6,2018
6,9,2015
7,7,2017
8,4,2020
9,12,2012


### Q20. Using `loc`, select rows 5 to 10 and only the columns `name`, `department`, `salary`.

In [54]:
df.loc[5:10,['name', 'department', 'salary']]

,name,department,salary
5,Divya Iyer,Engineering,88000.0
6,Aditya Kumar,Marketing,68000.0
7,Meera Joshi,Finance,98000.0
8,Vivek Singh,HR,51000.0
9,Ananya Das,Engineering,115000.0
10,Rahul Verma,Marketing,45000.0


---
## 🔴 HARD (Q21–Q30)
### Real interview questions — think carefully before coding

### Q21. ⭐ Interview Classic
What is the difference between `df['salary']` and `df[['salary']]`? Write a comment explaining the difference in output type, then prove it with code using `type()`.

In [57]:
# df['salary'] returns:  Series 1D
# df[['salary']] returns: Dataframe 2D
print(type(df['salary']))
print(type(df[['salary']]))


<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


### Q22. ⭐ Interview Classic
When would you use `at` over `loc`? Write a comment, then use both to access the `salary` of the employee at index 4 and compare.

In [58]:
# at is used to access or update a single value using row and column labels.
# It is generally faster than loc for retrieving one scalar value.
# loc is more flexible and can access one or multiple rows/columns.

# Using at
print(df.at[4, 'salary'])

# Using loc
print(df.loc[4, 'salary'])

130000.0
130000.0


### Q23. Select the `name` and `salary` columns for only the employees who are managers (`is_manager == True`) using `loc`.

In [66]:
mask = df[df['is_manager'] == True]
mask.loc[:,['name','salary']]

# df.loc[df['is_manager'] == True, ['name', 'salary']]
# df.loc[df['is_manager'], ['name', 'salary']]

,name,salary
0,Arjun Sharma,95000.0
2,Rohan Mehta,110000.0
4,Kiran Rao,130000.0
7,Meera Joshi,98000.0
9,Ananya Das,115000.0
12,Nikhil Gupta,NaN
14,Arjun Nambiar,145000.0
19,Tarun Bhatt,155000.0
21,Deepak Jain,120000.0


### Q24. Use `df.query()` to find employees who joined before 2015 AND have a salary above 100000.

In [71]:
df.query("joining_year< 2025 and salary >100000")['name']
# df

2       Rohan Mehta
4         Kiran Rao
9        Ananya Das
14    Arjun Nambiar
19      Tarun Bhatt
21      Deepak Jain
Name: name, dtype: object

### Q25. ⭐ Interview Classic
Using `iloc`, select a 3x3 sub-block from the middle of the DataFrame (rows 10–12, columns 4–6).

In [72]:
df.iloc[10:13,4:7]

,department,city,salary
10,Marketing,Jaipur,45000.0
11,Finance,Bangalore,92000.0
12,Engineering,Delhi,NaN


### Q26. Use `df.query()` with a Python variable. Store the value `90000` in a variable called `min_salary` and use it inside the query string to find all employees earning above it.

In [75]:
min_salary =90000
df.query("salary > @min_salary")

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40


### Q27. ⭐ Interview Classic
Select all rows where `department` is either `Finance` or `Engineering` using `loc` and the `.isin()` method.

In [80]:
df.loc[df['department'].isin(['Finance', 'Engineering'])]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16


### Q28. ⭐ Interview Classic
You are given a list of employee IDs: `[103, 107, 115, 120]`. Set `employee_id` as the index and use `loc` to select only those employees' records.

In [81]:
employee_ids = [103, 107, 115, 120]
df.set_index('employee_id').loc[employee_ids]

,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
employee_id,,,,,,,,,,,
103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55


### Q29. ⭐ Interview Classic
What happens when you use `loc` with a slice on a default integer index vs a custom index? Demonstrate by:
- Slicing `loc[1:3]` on the default index
- Setting `employee_id` as index and slicing `loc[103:107]`
- Write a comment explaining why the results differ.

In [ ]:
# Explanation: 
# loc always slices by LABELS, not positions.
# With the default integer index (0, 1, 2, ...), the labels happen to look
# like positions, so loc[1:3] returns rows with labels 1, 2, and 3.
# After setting employee_id as the index, the labels become employee IDs,
# so loc[103:107] returns all rows whose employee_id labels are between
# 103 and 107 (inclusive).

### Q30. ⭐ Interview Classic
Without using `df.filter()` or boolean indexing, use `loc` with `df.columns` to select only the columns that end with the letter `y` (e.g. `salary`, `city`). Print those column names first, then display the data.

In [84]:
cols = df.columns[df.columns.str.endswith('y')]

print(cols)

# df.loc[:, cols]

Index(['city', 'salary'], dtype='object')


---
## ✅ Done with Selecting Data!

| Method | Practiced in |
|--------|--------------|
| `df['col']` | Q1, Q21 |
| `df[['col1','col2']]` | Q2, Q21 |
| `df.iloc[]` | Q3, Q4, Q5, Q8, Q15, Q16, Q25 |
| `df.loc[]` | Q6, Q7, Q17, Q20, Q23, Q27, Q28, Q29, Q30 |
| `df.at[]` | Q9, Q22 |
| `df.iat[]` | Q10 |
| `df.filter()` | Q12, Q18, Q19 |
| `df.query()` | Q13, Q14, Q24, Q26 |

**Next up → Filtering Data 🚀**